name: chatbot_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_native_splash:
  color: "#1c1c1c"
  image: "assets/images/play_store_512.png"
  android: true
  ios: true